---

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: mariadb
  jpa:
    hibernate:
      ddl-auto: update

...